name: wasm
version: '0.1.0'
author: Ilya Rezvov
maintainer: rezvov.ilya@gmail.com
license: MIT
extra-source-files:
- README.md
- src/Language/Wasm/Parser.y
- src/Language/Wasm/Lexer.x
build-tools:
- alex >=3.1.3
- happy >=1.9.4
dependencies:
- base >=4.6

library:
  source-dirs: src
  ghc-options:
  - -Wwarn
  - -fwarn-incomplete-patterns
  - -fwarn-unused-imports
  dependencies:
  - array                >= 0.5
  - text                 >= 1.1
  - bytestring           >= 0.10
  - mtl                  >= 2.2
  - transformers         >= 0.4
  - containers           >= 0.5
  - utf8-string          >= 1.0
  - ieee754
  - deepseq
  - cereal
  - vector

tests:
  test:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - wasm == 0.1.0
    - filepath >=1.3 && <1.5
    - directory >= 1.3
    - text >=1.1 && <1.3
    - bytestring >=0.10 && <0.11
    - mtl ==2.2.1
    - tasty >=0.7
    - tasty-hunit >=0.4.1 && <0.10
